### ISSUE TITLE
Removing Stories from Following page and Collapsed Sidebar

### ISSUE THREAD

**Issue by MushyTales** [FrankerFaceZ/FrankerFaceZ#1678]
I have my Twitch shortcut set to my Following/Live page - despite having stories hidden in the FFZ settings, they are still on this page, and then also still on the collapsed side-bar.

I'd like an option(s) to disable/hide both of these examples. 

I have tried using the element picker in uBlock to remove them - and this works, *however* it then ends up sometimes messing with pinned banners/messages in chats, or messages about drops, or removes the profile pics/pictures in pinned messages/banners or if the streamer's picture is used in those kind of adverts etc it doesn't show it.

![Image](https://github.com/user-attachments/assets/c80021fc-10da-46fa-bd1f-5d40d59334d2)

**Comment by Nerxxy** [comment]
It would be nice to have stories removed from the following page and the collapsed navigation bar.



In the mean time you could try this:

For the collapsed side navigation you could use the Deck add-on with the setting to replace the side bar enabled, as the stories icon gets removed with/without the Hide Stories option enabled.

![Image](https://github.com/user-attachments/assets/ee1cf9ea-9e34-4774-be18-0878c2ac92d0)

![Image](https://github.com/user-attachments/assets/b8874ae2-71ba-4176-ab3a-70a211946836)


As for the stories in the following page you could use a CSS editor such as Stylus with this:

```
.common-centered-column > div > div:not(.ivrFkx) {
        display: none !important;
    }
```

Make sure the url-prefix is "https://www.twitch.tv/directory/following" as i dont know if will affect any other pages.

![Image](https://github.com/user-attachments/assets/26f09e45-1e1b-40ad-98d2-4aa0b7b0097a)

On the other hand, if u don't want to use the Deck add-on then it can be done with just CSS, copy all this:
![Image](https://github.com/user-attachments/assets/c8afb9dc-e3c6-4c76-94aa-b6d5f300288a)

If you need any more help let me know.

**Comment by missiah** [comment]
Oh yes please let us hide Stories from Following/Live page 🙏

**Comment by Trubbel** [comment]
If you use my addon within FFZ <sup>(Trubbel’s Utilities)</sup> then you should be able to hide it. \#selfad

**Comment by missiah** [comment]
> If you use my addon within FFZ (Trubbel’s Utilities) then you should be able to hide it. #selfad

omg you are awesome, thank you so much

**Comment by MiaowMinx** [comment]
> If you use my addon within FFZ (Trubbel’s Utilities) then you should be able to hide it. #selfad

Excellent add-on, but that particular feature doesn't seem to be working on the Following page, at least not for the section above live channels. Unless I'm misunderstanding and it's only meant to remove it from the sidebar...?

<img width="892" height="666" alt="Image" src="https://github.com/user-attachments/assets/8e268c20-3e49-4f2b-ac87-370a2de0d7cd" />

Thank you for working on it!

**Comment by Trubbel** [comment]
> > If you use my addon within FFZ (Trubbel’s Utilities) then you should be able to hide it. #selfad
> 
> Excellent add-on, but that particular feature doesn't seem to be working on the Following page, at least not for the section above live channels. Unless I'm misunderstanding and it's only meant to remove it from the sidebar...?
> 
> ...
> Thank you for working on it!

It was fixed in https://github.com/FrankerFaceZ/Add-Ons/pull/306.

Unsure what version the browser extensions are at currently, but if you use the userscript you'll always be up to date.
(Currently 4.77.11)

<img width="165" height="69" alt="Image" src="https://github.com/user-attachments/assets/76c34920-58ab-4ba3-825d-7d607e23c25c" />

**Comment by MushyTales** [comment]
> It was fixed in [FrankerFaceZ/Add-Ons#306](https://github.com/FrankerFaceZ/Add-Ons/pull/306).
> 
> Unsure what version the browser extensions are at currently, but if you use the userscript you'll always be up to date. (Currently 4.77.11)

I'm on 3.0.3 for your utilities and 4.77.11.2 for ffz and stories are still showing on the following page for me, hmmmm
