### ISSUE TITLE
Opening FFZ Settings in a new window results in a blank window

### ISSUE THREAD

**Issue by argowizbang** [FrankerFaceZ/FrankerFaceZ#1720]
**Describe the bug**
When using the "Open Settings in a New Window" button on the FFZ Control Center, the new window loads up the FFZ chat (as expected) and then eventually goes entirely blank without displaying the Control Center.

**To Reproduce**
1. Open the FFZ Control Center normally on any Twitch page.
2. Click on "Open Settings in a New Window" button
3. New window opens, loads chat, then goes blank

**Expected behavior**
FFZ Control Center loads up and functions properly in the new window.

**Screenshots**
Didn't see much of a need for a screenshot of a blank window, but here's a screenshot of every console error that happens:

<img width="1919" height="612" alt="Image" src="https://github.com/user-attachments/assets/4357bc39-7374-48ad-93ce-8754c937facb" />

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 141
 - Other Extensions: uBlock Origin (though it's disabled on Twitch)

**FFZ Logs (via FFZ Control Center > Home > Feedback >> Log)**:
https://logs.frankerfacez.com/e0f0517b-1e95-4320-9242-64688a1a074f

**Additional context**
This is in FFZ version 4.7.11. I can only seem to get this to happen in Firefox; in Chrome the Control Center loads up as expected in the new window. This also happens when loading in incognito mode, no other browser extensions or FFZ add-ons active/enabled.

**Comment by M-Reimer** [comment]
Ctrl + F5 seems to make the window at least show something.
But that doesn't help much as all scroll areas seem to be stuck.

**Comment by argowizbang** [comment]
Ctrl + F5 just gives me another blank screen, unfortunately.

The scrolling issue you mentioned though was fixed in FFZ version `4.77.11` that was released on July 21. You'll just either need to switch to the userscript version of FFZ which gets updates right away or wait for Mozilla to approve the update (which can take a while because Mozilla seems to _love_ taking their time with approvals).

**Comment by alkaris2** [comment]
This is still an issue. Open Settings in New Window just loads a blank window. And yes I'm using the Userscript version so it's on the latest `Version 4.77.11 dcb90e2`

A lot of Error 404 messages, and inaccessible scripts, general JavaScript errors, Undefined errors, Source Map errors and warnings, CSP warnings when trying to access certain external resources hosted on Cloudflare CDN, and GraphQL errors on requests.

**Comment by alkaris2** [comment]
What do you mean closed and completed? It's still broken.

<img width="1067" height="721" alt="Image" src="https://github.com/user-attachments/assets/c95990b7-b6ae-4938-9f97-10721aea5b3d" />
